minio:
  url: http://localhost:9000
  accessName: gclVEXMM4U28cCxBy0Yd
  accessSecret: nimfVgxPiW0EW6MxmVuABCKZWfXThn5KwePWeCK1
  bucketName: pkg-fetch
redis:
  host: localhost
  port: 6379
  password: lsk123456
  db: 2
paging:
  items: 10
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: lsk123456
    url: jdbc:mysql://localhost:3306/package_fetch_sys
